namespace Akka.Pathfinder.DemoLayout;

public static class GermanRailwayData
{
    public static readonly List<CityData> Cities =
    [
        new("Kiel", 50, 2, TransportType.Terminal),
        new("Westerland (Sylt)", 42, 0, TransportType.Terminal),
        new("Flensburg", 45, 1, TransportType.Terminal),
        new("Neumünster", 48, 5, TransportType.Station),
        new("Hamburg", 50, 12, TransportType.Station, 12, 4),
        new("Lübeck", 58, 10, TransportType.Station),
        new("Rostock", 75, 5, TransportType.Terminal),
        new("Stralsund", 85, 4, TransportType.Terminal),
        new("Schwerin", 65, 10, TransportType.Station),
        new("Bremen", 35, 15, TransportType.Station),
        new("Oldenburg", 28, 16, TransportType.Station),
        new("Emden", 18, 12, TransportType.Terminal),
        new("Lüneburg", 55, 18, TransportType.Station),
        new("Uelzen", 53, 22, TransportType.Station),
        new("Celle", 48, 26, TransportType.Station),
        new("Wittenberge", 65, 20, TransportType.Station),
        new("Ludwigslust", 60, 18, TransportType.Station),

        new("Berlin", 85, 25, TransportType.Station, 16, 2),
        new("Potsdam", 82, 26, TransportType.Station),
        new("Frankfurt (Oder)", 95, 28, TransportType.Terminal),
        new("Cottbus", 92, 38, TransportType.Station),
        new("Görlitz", 98, 55, TransportType.Terminal),
        new("Magdeburg", 70, 35, TransportType.Station),
        new("Halle (Saale)", 72, 43, TransportType.Station),
        new("Leipzig", 75, 45, TransportType.Station, 21),
        new("Wittenberg (Lutherstadt)", 82, 35, TransportType.Station),
        new("Bitterfeld", 78, 40, TransportType.Station),
        new("Dresden", 85, 50, TransportType.Terminal),
        new("Chemnitz", 80, 55, TransportType.Station),
        new("Erfurt", 60, 50, TransportType.Station),
        new("Weimar", 64, 50, TransportType.Station),
        new("Jena", 70, 50, TransportType.Station),
        new("Naumburg (Saale)", 70, 48, TransportType.Station),
        new("Saalfeld (Saale)", 68, 58, TransportType.Station),
        new("Gera", 68, 52, TransportType.Station),
        new("Eisenach", 55, 52, TransportType.Station),
        new("Hanover", 45, 30, TransportType.Station, 12),
        new("Braunschweig", 52, 32, TransportType.Station),
        new("Wolfsburg", 55, 30, TransportType.Station),
        new("Göttingen", 45, 42, TransportType.Station),
        new("Osnabrück", 25, 30, TransportType.Station),
        new("Münster", 20, 35, TransportType.Station),
        new("Bielefeld", 30, 35, TransportType.Station),
        new("Dortmund", 15, 40, TransportType.Station, 16, 2),
        new("Essen", 12, 42, TransportType.Station, 13),
        new("Duisburg", 10, 43, TransportType.Station, 12),
        new("Düsseldorf", 9, 46, TransportType.Station, 16, 4),
        new("Wuppertal", 14, 45, TransportType.Station),
        new("Cologne", 10, 50, TransportType.Station, 11, 2),
        new("Aachen", 2, 52, TransportType.Terminal),
        new("Bonn", 11, 55, TransportType.Station),
        new("Koblenz", 15, 60, TransportType.Station),
        new("Trier", 5, 68, TransportType.Station),
        new("Saarbrücken", 8, 75, TransportType.Terminal),

        new("Kassel", 45, 50, TransportType.Station),
        new("Gießen", 35, 55, TransportType.Station),
        new("Fulda", 48, 58, TransportType.Station),
        new("Frankfurt am Main", 25, 65, TransportType.Station, 25, 4),
        new("Wiesbaden", 20, 64, TransportType.Station),
        new("Mainz", 21, 66, TransportType.Station),
        new("Darmstadt", 26, 68, TransportType.Station),
        new("Hanau", 30, 65, TransportType.Station),
        new("Würzburg", 45, 65, TransportType.Station),
        new("Aschaffenburg", 35, 66, TransportType.Station),
        new("Mannheim", 25, 75, TransportType.Station),
        new("Heidelberg", 28, 76, TransportType.Station),
        new("Karlsruhe", 20, 85, TransportType.Station),
        new("Pforzheim", 25, 87, TransportType.Station),
        new("Stuttgart", 30, 85, TransportType.Station, 16),
        new("Heilbronn", 32, 80, TransportType.Station),
        new("Tübingen", 31, 90, TransportType.Station),
        new("Freiburg", 15, 95, TransportType.Terminal),
        new("Ulm", 45, 85, TransportType.Station),
        new("Lindau", 48, 105, TransportType.Terminal),
        new("Oberstdorf", 55, 110, TransportType.Terminal),
        new("Augsburg", 55, 88, TransportType.Station),
        new("Ingolstadt", 58, 83, TransportType.Station),
        new("Munich", 65, 95, TransportType.Terminal, 32, 2),
        new("Rosenheim", 75, 97, TransportType.Station),
        new("Garmisch-Partenkirchen", 62, 105, TransportType.Terminal),
        new("Nuremberg", 55, 70, TransportType.Station, 22),
        new("Bayreuth", 62, 65, TransportType.Station),
        new("Erlangen", 54, 68, TransportType.Station),
        new("Regensburg", 65, 75, TransportType.Station),
        new("Siegburg/Bonn", 12, 53, TransportType.Station),
        new("Montabaur", 18, 58, TransportType.Station),
        new("Limburg South", 20, 60, TransportType.Station),
        new("Baden-Baden", 19, 87, TransportType.Station),
        new("Offenburg", 18, 90, TransportType.Station),
        new("Bergedorf", 54, 12, TransportType.Station),
        new("Passau", 80, 80, TransportType.Terminal),

        new("B-East", 87, 25, TransportType.Station),
        new("B-South", 85, 27, TransportType.Station),
        new("B-Spandau", 81, 24, TransportType.Station),
        new("B-Freight-South", 88, 30, TransportType.Station),
        new("Seddin-Yard", 78, 32, TransportType.Terminal),
        new("B-Depot-Rummelsburg", 89, 25, TransportType.Depot),

        new("HH-Altona", 48, 11, TransportType.Station),
        new("HH-Harburg", 50, 14, TransportType.Station),
        new("HH-Freight-Maschen", 52, 16, TransportType.Station),
        new("Maschen-Yard", 53, 17, TransportType.Terminal),
        new("HH-Depot-Eidelstedt", 47, 10, TransportType.Depot),
        new("HH-Freight-Altona", 47, 11, TransportType.Station),

        new("M-East", 67, 95, TransportType.Station),
        new("M-Pasing", 63, 95, TransportType.Station),
        new("M-Freight-North", 65, 92, TransportType.Station),
        new("Muenchen-North-Yard", 65, 91, TransportType.Terminal),
        new("M-Depot", 66, 96, TransportType.Depot),

        new("F-South", 26, 66, TransportType.Station),
        new("F-Airport", 22, 67, TransportType.Station),
        new("F-Freight", 24, 66, TransportType.Station),
        new("F-Depot", 26, 64, TransportType.Depot),

        new("Bochum", 18, 40, TransportType.Station),
        new("Duisburg-Freight", 11, 43, TransportType.Station),
        new("Dortmund-Freight", 16, 40, TransportType.Station),
        new("Hamm-Yard", 20, 38, TransportType.Terminal),
        new("Hagen-Vorhalle-Yard", 17, 43, TransportType.Terminal),
        new("Dortmund-Depot", 16, 39, TransportType.Depot),

        new("K-Freight-Eifeltor", 9, 52, TransportType.Station),
        new("K-Depot", 11, 49, TransportType.Depot),

        new("N-Freight", 56, 71, TransportType.Station),
        new("Nuernberg-Yard", 57, 72, TransportType.Terminal),
        new("N-Depot", 56, 69, TransportType.Depot),
        new("L-Freight", 77, 45, TransportType.Station),
        new("L-Depot", 76, 44, TransportType.Depot),
        new("MA-Freight", 26, 76, TransportType.Station),
        new("Mannheim-Yard", 27, 77, TransportType.Terminal),
        new("KA-Freight", 21, 86, TransportType.Station),
        new("S-Freight", 31, 86, TransportType.Station),
        new("Kornwestheim-Yard", 32, 84, TransportType.Terminal),
        new("S-Depot", 31, 84, TransportType.Depot),
        new("HB-Freight", 36, 16, TransportType.Station),
        new("HB-Depot", 34, 15, TransportType.Depot),
        new("DD-Depot", 86, 50, TransportType.Depot),
        new("ER-Depot", 55, 68, TransportType.Depot),
        new("BR-Central", 35, 10, TransportType.Station),
        new("BR-Freight", 34, 10, TransportType.Station)
    ];

    public static readonly Dictionary<string, string> CodeToName = new()
    {
        { "HH-Central", "Hamburg" },
        { "HB-Central", "Bremen" },
        { "B-Central", "Berlin" },
        { "M-Central", "Munich" },
        { "F-Central", "Frankfurt am Main" },
        { "K-Central", "Cologne" },
        { "S-Central", "Stuttgart" },
        { "MA-Central", "Mannheim" },
        { "KA-Central", "Karlsruhe" },
        { "UL-Central", "Ulm" },
        { "A-Central", "Augsburg" },
        { "N-Central", "Nuremberg" },
        { "MD-Central", "Magdeburg" },
        { "L-Central", "Leipzig" },
        { "ER-Central", "Erfurt" },
        { "AC-Central", "Aachen" },
        { "D-Central", "Düsseldorf" },
        { "E-Central", "Essen" },
        { "BO-Central", "Bochum" },
        { "DO-Central", "Dortmund" },
        { "DU-Central", "Duisburg" },
        { "MS-Central", "Münster" },
        { "BI-Central", "Bielefeld" },
        { "P-Central", "Potsdam" },
        { "DD-Central", "Dresden" },
        { "KI-Central", "Kiel" },
        { "LU-Central", "Lübeck" },
        { "WI-Central", "Wiesbaden" },
        { "WU-Central", "Würzburg" },
        { "OS-Central", "Osnabrück" },
        { "BS-Central", "Braunschweig" },
        { "HLE-Central", "Halle (Saale)" },
        { "C-Central", "Cottbus" },
        { "FR-Central", "Freiburg" },
        { "KS-Wilhelmshoehe", "Kassel" },
        { "KS-Central", "Kassel" },
        { "FD-Central", "Fulda" },
        { "GI-Central", "Gießen" },
        { "OL-Central", "Oldenburg" },
        { "W-Central", "Wuppertal" },
        { "M-East", "M-East" },
        { "M-Pasing", "M-Pasing" },
        { "B-East", "B-East" },
        { "B-South", "B-South" },
        { "B-Spandau", "B-Spandau" },
        { "HH-Altona", "HH-Altona" },
        { "HH-Harburg", "HH-Harburg" },
        { "F-South", "F-South" },
        { "F-Airport", "F-Airport" },
        { "HH-Freight-Maschen", "HH-Freight-Maschen" },
        { "Maschen-Yard", "Maschen-Yard" },
        { "K-Freight-Eifeltor", "K-Freight-Eifeltor" },
        { "M-Freight-North", "M-Freight-North" },
        { "Muenchen-North-Yard", "Muenchen-North-Yard" },
        { "F-Freight", "F-Freight" },
        { "N-Freight", "N-Freight" },
        { "Nuernberg-Yard", "Nuernberg-Yard" },
        { "HB-Freight", "HB-Freight" },
        { "DO-Freight", "Dortmund-Freight" },
        { "DU-Freight", "Duisburg-Freight" },
        { "L-Freight", "L-Freight" },
        { "B-Freight-South", "B-Freight-South" },
        { "MA-Freight", "MA-Freight" },
        { "KA-Freight", "KA-Freight" },
        { "S-Freight", "S-Freight" },
        { "Kornwestheim-Yard", "Kornwestheim-Yard" },
        { "BR-Central", "BR-Central" },
        { "BR-Freight", "BR-Freight" },
        { "HH-Freight-Altona", "HH-Freight-Altona" },
        { "Hagen-Vorhalle-Yard", "Hagen-Vorhalle-Yard" },
        { "Hamm-Yard", "Hamm-Yard" },
        { "Seddin-Yard", "Seddin-Yard" },
        { "M-Depot", "M-Depot" },
        { "HH-Depot-Eidelstedt", "HH-Depot-Eidelstedt" },
        { "B-Depot-Rummelsburg", "B-Depot-Rummelsburg" },
        { "K-Depot", "K-Depot" },
        { "F-Depot", "F-Depot" },
        { "N-Depot", "N-Depot" },
        { "L-Depot", "L-Depot" },
        { "S-Depot", "S-Depot" },
        { "HB-Depot", "HB-Depot" },
        { "DO-Depot", "Dortmund-Depot" },
        { "DD-Depot", "DD-Depot" },
        { "ER-Depot", "ER-Depot" }
    };

    public record CityData(string Name, int X, int Y, TransportType Type, int Platforms = 2, int UndergroundPlatforms = 0);
}